image: alpine:latest

stages:
  - build
  - deploy

variables:
  GRADLE_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"

default:
  before_script:
    - "apk add --no-cache git openjdk17"

build:
  stage: build
  script:
    - "./gradlew --build-cache assemble shadowJar"
    - "./gradlew check"
    - "./gradlew publish"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - "*/build"
      - "*/.gradle"
      - ".m2/repository"
  artifacts:
    paths:
      - "*/build/libs/*.jar"
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - "./gradlew javadoc"
    - "mv src/site public"
    - "mkdir -p public/javadoc"
    - "mv paper/build/docs/javadoc public/javadoc/paper"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "*/build"
      - "*/.gradle"
      - ".m2/repository"
  artifacts:
    paths:
      - "public"
  only:
    - master
