name: "${project.name}"
description: "${project.description}"
author: "aecsocket"
version: "${project.version}"
api-version: "1.16"
main: "${project.groupId}.${project.artifactId}.NaturaPlugin"
depend: [ "ProtocolLib" ]